openapi: "3.0.1"
info:
  title: gateways project
  version: 1.0.0
  description: This sample project is managing gateways - master devices that control multiple peripheral devices.
tags:
  - name: Gateways
  - name: Peripherals
paths:
  /gateways:
    get:
      summary: List all getway
      operationId: getAllGateways
      tags:
        - Gateways
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewaysResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    post:
      summary: create gateway
      operationId: createGateway
      tags:
        - Gateways
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GatewayRequest'

      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'

  /gateways/{serialNumber}:
    get:
      summary: retive gateway by serial number
      operationId: getGatewayBySerialNumber
      tags:
        - Gateways
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayResponse'
        '400':
          description: invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    put:
      summary: update gateway info
      operationId: updateGateway
      tags:
        - Gateways
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GatewayUpdateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GatewayResponse'
        '400':
          description: invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    delete:
      summary: delete gateway
      operationId: deleteGateway
      tags:
        - Gateways
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
      responses:
        '204':
          description: no content
        '400':
          description: invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'

  /gateways/{serialNumber}/peripherals:
    get:
      summary: List all peripheral devices
      operationId: getAllPeripherals
      tags:
        - Peripherals
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeripheralsResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    post:
      summary: create peripheral device
      operationId: createPeripheral
      tags:
        - Peripherals
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeripheralRequest'

      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeripheralResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
  /gateways/{serialNumber}/peripherals/{uid}:
    get:
      summary: |
        retive peripheral device associated to spacific gateway
        by gateway serialNumber and peripheral device unique identifer
      operationId: getPeripheralBySerialNumberAndUid
      tags:
        - Peripherals
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
        - in: path
          name: uid
          required: true
          schema:
            type: number
            description: peripheral unique identifer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeripheralResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    put:
      summary: update peripheral device info
      operationId: updatePeripheral
      tags:
        - Peripherals
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
        - in: path
          name: uid
          required: true
          schema:
            type: number
            description: peripheral unique identifer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PeripheralUpdateRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeripheralResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
    delete:
      summary: delete peripheral device
      operationId: deletePeripheral
      tags:
        - Peripherals
      parameters:
        - in: path
          name: serialNumber
          required: true
          schema:
            type: string
            description: gateway serial number
        - in: path
          name: uid
          required: true
          schema:
            type: number
            description: peripheral unique identifer
      responses:
        '204':
          description: no content
        '400':
          description: bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '404':
          description: Resource Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorDetails'

components:
  schemas:
    GatewaysResponse:
      type: array
      items:
        $ref: '#/components/schemas/GatewayResponse'
      example:
        - serialNumber: 246810
          name: HeadPhone
          ipv4: 210.200.50.1

    GatewayResponse:
      type: object
      properties:
        serialNumber:
          type: string
        name:
          type: string
        ipv4:
          type: string
        peripheralDevices:
          $ref: '#/components/schemas/PeripheralsResponse'
    GatewayRequest:
      type: object
      required:
        - serialNumber
        - name
        - ipv4
      properties:
        serialNumber:
          type: string
        name:
          type: string
        ipv4:
          type: string
          pattern: '^((0|1\d?\d?|2[0-4]?\d?|25[0-5]?|[3-9]\d?)\.){3}(0|1\d?\d?|2[0-4]?\d?|25[0-5]?|[3-9]\d?)$'
    GatewayUpdateRequest:
      type: object
      required:
        - name
        - ipv4
      properties:
        name:
          type: string
        ipv4:
          type: string
          pattern: '^((0|1\d?\d?|2[0-4]?\d?|25[0-5]?|[3-9]\d?)\.){3}(0|1\d?\d?|2[0-4]?\d?|25[0-5]?|[3-9]\d?)$'

    PeripheralsResponse:
      type: array
      items:
        $ref: '#/components/schemas/PeripheralResponse'
    PeripheralResponse:
      type: object
      properties:
        uid:
          type: number
        vendor:
          type: string
        createdDate:
          type: string
          format: date
        status:
          $ref: '#/components/schemas/Status'

    PeripheralRequest:
      type: object
      required:
        - uid
        - vendor
        - status
      properties:
        uid:
          type: number
        vendor:
          type: string
        status:
          $ref: '#/components/schemas/Status'
    PeripheralUpdateRequest:
      type: object
      required:
        - vendor
        - status
      properties:
        vendor:
          type: string
        status:
          $ref: '#/components/schemas/Status'

    Status:
      type: string
      enum:
        - online
        - offline
    ErrorDetails:
      type: object
      required:
        - code
        - message
      properties:
        date:
          type: string
          format: datetime
        status:
          type: string
        error:
          type: string
        uri:
          type: string
        message:
          type: string
